const assert=require("node:assert/strict"), fs=require("node:fs"), path=require("node:path"), vm=require("node:vm"), test=require("node:test");
function harness(){const context=vm.createContext({window:{location:{pathname:"/"}},document:{addEventListener(){}}});vm.runInContext(fs.readFileSync(path.join(__dirname,"../frontend/app.js"),"utf8"),context);return code=>vm.runInContext(code,context);}
test("same id mode/revision changes invalidate hidden recipe but same revision retains choice",()=>{const run=harness();run('const p={id:"same",mode:"t2v",connector_revision:"r1",recipe_id:"A4"};syncRecipeSelectionScope(p);state.recipeSelections.same="B8";syncRecipeSelectionScope(p)');assert.equal(run('state.recipeSelections.same'),"B8");run('syncRecipeSelectionScope({...p,connector_revision:"r2"})');assert.equal(run('state.recipeSelections.same'),undefined);run('state.recipeSelections.same="A4";syncRecipeSelectionScope({...p,mode:"i2v"})');assert.equal(run('state.recipeSelections.same'),undefined);});
for(const mode of ["i2v","l2v","fl2v","reference","hybrid"])test(mode+" requires exact qualified profile or own acceptance task",()=>{const run=harness();run(`const p={id:"own",connector_owner:"owner",mode:"${mode}",duration:15,orientation:"portrait",execution_profile:{profile_id:"profile",version:"v1"}}`);assert.match(run('previewUnavailable(p)'),/暂不能开始/);run('state.recipeCatalog={multimodal_profiles:[{profile_id:"profile",version:"old",qualified:true}]}');assert.match(run('previewUnavailable(p)'),/暂不能开始/);run('state.recipeCatalog.multimodal_profiles=[{profile_id:"profile",version:"v1",qualified:false,acceptance_tasks:["other"]}]');assert.match(run('previewUnavailable(p)'),/暂不能开始/);run('state.recipeCatalog.multimodal_profiles[0].acceptance_tasks=["own"]');assert.equal(run('previewUnavailable(p)'),"");run('state.recipeCatalog.multimodal_profiles[0].qualified=true');assert.equal(run('previewUnavailable(p)'),"");});

test("connector first-frame start ignores a stale t2v recipe selection",async()=>{
  const elements=new Map(); const context=vm.createContext({window:{location:{pathname:"/"}},document:{addEventListener(){},getElementById(id){if(!elements.has(id))elements.set(id,{classList:{remove(){}}});return elements.get(id);}}});
  vm.runInContext(fs.readFileSync(path.join(__dirname,"../frontend/app.js"),"utf8"),context);
  if(!vm.runInContext('startStage.toString().includes("h3_start_preview")',context))return;
  vm.runInContext('state.project={id:"same",connector_owner:"owner",mode:"i2v",duration:15,orientation:"portrait",execution_profile:{profile_id:"p",version:"v"},stages:{context_ir:{output_id:"o"},preview:{}}};state.recipeCatalog={multimodal_profiles:[{profile_id:"p",version:"v",qualified:true}]};state.recipeSelections.same="B8";runAction=fn=>fn();window.h3BrowserAction=async(name,args)=>({name,args});',context);
  const result=await vm.runInContext('startStage("preview",false)',context);assert.equal(result.name,"h3_start_preview");assert.equal(result.args.expected_output_id,"o");
});
