worker_processes auto;
error_log /dev/stderr warn;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    log_format api '$remote_addr $request_method $uri $status $request_time';
    access_log /dev/stdout api;
    server_tokens off;

    server {
        listen 192.168.2.66:4000 ssl default_server;
        server_name 192.168.2.66;
        ssl_certificate /lan-tls/server.crt;
        ssl_certificate_key /lan-tls/server.key;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_session_cache shared:TLS:10m;
        ssl_session_timeout 10m;
        client_max_body_size 32m;
        include /etc/nginx/lan-api.conf;
    }

    server {
        listen 192.168.2.66:4000 ssl;
        server_name ai-x10drg.taild500c8.ts.net;
        ssl_certificate /tls/ai-x10drg.taild500c8.ts.net.crt;
        ssl_certificate_key /tls/ai-x10drg.taild500c8.ts.net.key;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_session_cache shared:TLS:10m;
        ssl_session_timeout 10m;
        client_max_body_size 32m;

        include /etc/nginx/lan-api.conf;
    }
    server {
        listen 192.168.2.66:4002;
        server_name 192.168.2.66;
        client_max_body_size 32m;
        include /etc/nginx/lan-api.conf;
    }

}
