const assert = require("node:assert/strict");
const fs = require("node:fs");
const vm = require("node:vm");
const path = require("node:path");
const context = {window: {}};
vm.runInNewContext(fs.readFileSync(path.join(__dirname, "../ai_router/static/endpoint-summary.js"), "utf8"), context);
const ui = context.window.EndpointSummary;
assert.equal(ui.device({id: "ai-qwen38-27b", node: "ai"}), "V100 TP4");
assert.equal(ui.device({node: "amd"}), "AMD 395");
assert.equal(ui.device({id: "ivan-v10016-bonsai2-128k", node: "ivan-v10016"}), "V100 16G");
assert.equal(ui.device({id: "ivan-v10016-bonsai2-196k", node: "ivan-v10016"}), "V100 16G");
assert.equal(ui.device({id: "ivan-qwen38-flash-128k", node: "ivan"}), "IVAN");
assert.equal(ui.concurrency({max_concurrency: 6}, {detail: {running: 0}}), "0 / 6");
assert.equal(ui.concurrency({max_concurrency: 6}, {}), "未知 / 6");
assert.equal(ui.automatic({auto_candidate: true, enabled: true}, {healthy: false}), "已加入 · 健康检查未通过");
assert.equal(ui.automatic({auto_candidate: true, enabled: true}, {healthy: true}), "已加入 · 仍需请求检查");
assert.equal(ui.automatic({auto_candidate: false}, {healthy: true}), "未加入");
const rows = [{endpoint: {enabled: false}}, {endpoint: {enabled: true}}];
assert.equal(ui.visible(rows, false).length, 1);
assert.equal(ui.visible(rows, true).length, 2);
assert.equal(rows.length, 2);
console.log("endpoint summary: PASS");
